[platformio]
default_envs = cyd, elecrow_5
boards_dir = boards

[env:cyd]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
  -D USER_SETUP_LOADED=1
  -include include/User_Setup.h
lib_deps =
  bodmer/TFT_eSPI @ ^2.5.43
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#v1.4
  bblanchon/ArduinoJson @ ^7.4.2
  knolleary/PubSubClient @ ^2.8

[env:elecrow_5]
platform = espressif32
board = elecrow-dis07050h-v3
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions-elecrow.csv
build_flags =
  -D SHOWDECK_ELECROW_5=1
  -D BOARD_HAS_PSRAM
  -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  lovyan03/LovyanGFX @ ^1.2.7
  bblanchon/ArduinoJson @ ^7.4.2
  knolleary/PubSubClient @ ^2.8
