#pragma once

const char WEB_UI[] PROGMEM = R"HTML(
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Show Deck</title><style>
:root{color-scheme:dark;--bg:#0d1215;--panel:#172025;--line:#34434a;--gold:#efb54a;--muted:#9cabb2}
*{box-sizing:border-box}body{font-family:system-ui,-apple-system,sans-serif;margin:0;background:var(--bg);color:#f7f3e8}
header{position:sticky;top:0;display:flex;align-items:center;justify-content:space-between;background:#0d1215f2;padding:13px 18px;border-bottom:1px solid #29353a;z-index:3}
h1{font-size:21px;margin:0;color:var(--gold);letter-spacing:.04em}main{max-width:760px;margin:auto;padding:18px}
button,input,select,textarea{font:inherit;border:1px solid var(--line);border-radius:8px;background:#0e1518;color:white;padding:10px}
button{font-weight:700;cursor:pointer}.small{width:auto;padding:8px 12px}.primary{background:#9a6414;border-color:var(--gold)}
.help-dot{display:inline-flex;align-items:center;justify-content:center;width:18px;height:18px;padding:0;margin-left:4px;border:1px solid #60747d;border-radius:50%;background:#26343a;color:#dce7eb;font-size:11px;line-height:1;vertical-align:middle}
.tabs{display:flex;gap:7px;overflow:auto;margin-bottom:12px}.tabs button{width:auto;white-space:nowrap}.active{background:#9a6414;border-color:var(--gold)}
.pagebar{display:flex;align-items:end;gap:10px;background:var(--panel);padding:12px;border-radius:12px 12px 0 0}.pagebar>div{flex:1}.pagebar button{width:auto;white-space:nowrap}
label{display:block;color:var(--muted);font-size:12px;margin:0 0 4px}.deck-shell{background:#050708;border:1px solid #34444b;border-radius:0 0 16px 16px;padding:10px;box-shadow:0 14px 50px #0008}
.deck-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;aspect-ratio:320/210}
.deck-button{position:relative;min-width:0;border:1px solid #ffffff28;border-radius:9px;overflow:hidden;background:var(--button,#315b68);display:flex;align-items:center;justify-content:center;text-align:center;padding:5px;color:white;box-shadow:inset 0 1px #ffffff1c;touch-action:none;user-select:none}
.deck-button.dragging{opacity:.38;outline:2px solid var(--gold)}.deck-button.drop-target{outline:3px solid #86e5ad;outline-offset:-3px}
.deck-button canvas{position:absolute;inset:0;width:100%;height:100%}.deck-button .emoji{font-size:clamp(25px,6vw,46px);line-height:1}
.deck-button .button-label{position:absolute;z-index:1;left:4px;right:22px;bottom:4px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:clamp(10px,2vw,14px);font-weight:800;text-shadow:0 1px 2px #000,0 0 5px #000}
.more{position:absolute;right:3px;bottom:3px;width:20px;height:18px;padding:0;border:0;background:#0007;border-radius:5px;color:white;line-height:12px}
.actions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.status{min-height:24px;margin-top:12px;color:#86e5ad}.hint{font-size:12px;color:var(--muted)}
.deck-tip{margin:9px 2px 0}.help-content{line-height:1.48}.help-content h3{font-size:15px;color:var(--gold);margin:16px 0 5px}.help-content h3:first-child{margin-top:0}.help-content p,.help-content ul{margin:6px 0}.help-content code{background:#0d1417;border-radius:4px;padding:2px 5px;color:#d5f4df}
dialog{width:min(620px,calc(100% - 24px));border:1px solid #405159;border-radius:15px;background:var(--panel);color:white;padding:0;box-shadow:0 30px 100px #000}dialog::backdrop{background:#000b}
.modal-head{display:flex;justify-content:space-between;align-items:center;padding:14px 16px;border-bottom:1px solid #314047}.modal-head h2{font-size:18px;margin:0;color:var(--gold)}.modal-body{padding:16px}.row{display:grid;grid-template-columns:repeat(2,1fr);gap:11px}.field{margin-bottom:11px}.field input,.field select,.field textarea{width:100%}
.asset-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.modal-foot{display:flex;justify-content:flex-end;gap:8px;padding:13px 16px;border-top:1px solid #314047}.modal-foot button{width:auto}
@media(max-width:560px){main{padding:10px}.deck-grid{gap:5px}.row{grid-template-columns:1fr}.actions{grid-template-columns:1fr}.deck-shell{padding:6px}}
</style></head><body><header><h1>SHOW DECK</h1><button class="small" onclick="openSettings()">Settings</button></header><main>
<div class="tabs" id="tabs"></div>
<section class="pagebar"><div><label>Page name <button type="button" class="help-dot" onclick="showHelp('pages')" aria-label="Page help">?</button></label><input id="pageName" style="width:100%" oninput="cfg.pages[page].name=this.value;renderTabs()"></div><button onclick="addPage()">Add page</button><button onclick="deletePage()">Delete page</button></section>
<section class="deck-shell"><div class="deck-grid" id="deck"></div></section>
<p class="hint deck-tip">Drag buttons to rearrange them. On a touchscreen, press and hold, then drag. <button type="button" class="help-dot" onclick="showHelp('arrange')" aria-label="Rearranging help">?</button></p>
<section class="actions"><button class="primary" onclick="save()">Save to Show Deck</button><button onclick="downloadConfig()">Export JSON</button><button onclick="document.querySelector('#configFile').click()">Import JSON</button><button onclick="location.href='/api/reboot'">Reboot Show Deck</button><input hidden id="configFile" type="file" accept="application/json" onchange="importConfig(this)"></section>
<div class="status" id="status"></div><p class="hint">Use the three-dot control on a button to edit it. Swipe on the physical Show Deck to change pages.</p>
</main>

<dialog id="buttonDialog"><div class="modal-head"><h2 id="buttonTitle">Button</h2><button class="small" onclick="finishButton()">Done</button></div><div class="modal-body">
 <div class="row"><div class="field"><label>Label <button type="button" class="help-dot" onclick="showHelp('label')">?</button></label><input id="bLabel" oninput="edit('label',this.value)"><div class="hint">Optional title shown along the bottom of the physical button.</div></div><div class="field"><label>Button color <button type="button" class="help-dot" onclick="showHelp('color')">?</button></label><input id="bColor" type="color" oninput="edit('color',this.value)"><div class="hint">Used as the background when there is no image, and behind emoji artwork.</div></div></div>
 <div class="field"><label>Emoji or short text icon <button type="button" class="help-dot" onclick="showHelp('emoji')">?</button></label><input id="bIcon" placeholder="Example: flame emoji" oninput="editIcon(this.value)"><div class="hint">The emoji is automatically converted to display artwork when you press Done.</div></div>
 <div class="field"><label>Artwork <button type="button" class="help-dot" onclick="showHelp('artwork')">?</button></label><div class="asset-actions"><button onclick="document.querySelector('#imageFile').click()">Upload image</button><input hidden id="imageFile" type="file" accept="image/*" onchange="uploadImage(this)"><button onclick="removeImage()">Remove artwork</button></div><div class="hint">Images fill the whole button. GIF uploads currently use the first frame.</div></div>
 <div class="row"><div class="field"><label>Action <button type="button" class="help-dot" onclick="showHelp('action')">?</button></label><select id="bType" onchange="editType(this.value)"><option>none</option><option>setup</option><option>espnow</option><option>mqtt</option><option>http</option><option>page</option></select><div class="hint" id="actionHelp"></div></div><div class="field"><label>Target <button type="button" class="help-dot" onclick="showHelp('target')">?</button></label><input id="bTarget" oninput="edit('target',this.value)"><div class="hint" id="targetHelp"></div></div></div>
 <div class="field"><label>Payload or command <button type="button" class="help-dot" onclick="showHelp('payload')">?</button></label><textarea id="bPayload" rows="4" oninput="edit('payload',this.value)"></textarea><div class="hint" id="payloadHelp"></div></div>
</div><div class="modal-foot"><button onclick="resetButton()">Reset button</button><button class="primary" onclick="finishButton()">Done</button></div></dialog>

<dialog id="settingsDialog"><div class="modal-head"><h2>Show Deck Settings</h2><button class="small" onclick="$('settingsDialog').close()">Close</button></div><div class="modal-body"><div class="row">
 <div class="field"><label>Deck name <button type="button" class="help-dot" onclick="showHelp('name')">?</button></label><input id="name"></div><div class="field"><label>Screen brightness (20-255) <button type="button" class="help-dot" onclick="showHelp('brightness')">?</button></label><input id="brightness" type="number" min="20" max="255"></div>
 <div class="field"><label>Wi-Fi SSID (optional) <button type="button" class="help-dot" onclick="showHelp('wifi')">?</button></label><input id="ssid"><div class="hint">Leave blank to use only the ShowDeck-Setup hotspot.</div></div><div class="field"><label>Wi-Fi password</label><input id="password" type="password" placeholder="Leave unchanged"><div class="hint">Blank keeps the currently saved password.</div></div>
 <div class="field"><label>MQTT host (optional) <button type="button" class="help-dot" onclick="showHelp('mqtt')">?</button></label><input id="mqttHost"><div class="hint">Broker hostname or IP address, without http://.</div></div><div class="field"><label>MQTT port</label><input id="mqttPort" type="number"><div class="hint">Usually 1883 for an unencrypted local broker.</div></div>
 <div class="field"><label>MQTT username</label><input id="mqttUser"></div><div class="field"><label>MQTT password</label><input id="mqttPassword" type="password" placeholder="Leave unchanged"></div>
 <div class="field"><label>ESP-NOW channel (1-13) <button type="button" class="help-dot" onclick="showHelp('espnow')">?</button></label><input id="espnowChannel" type="number" min="1" max="13"><div class="hint">Must match every receiver. When joined to Wi-Fi, use that access point's channel.</div></div>
</div></div><div class="modal-foot"><button class="primary" onclick="collectSettings();$('settingsDialog').close()">Done</button></div></dialog>

<dialog id="helpDialog"><div class="modal-head"><h2 id="helpTitle">Help</h2><button class="small" onclick="$('helpDialog').close()">Close</button></div><div class="modal-body help-content" id="helpBody"></div><div class="modal-foot"><button class="primary" onclick="$('helpDialog').close()">Got it</button></div></dialog>

<script>
let cfg,page=0,editing=0,dragFrom=-1,touchDrag=null;
const $=id=>document.getElementById(id),esc=s=>(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function blankButton(){return{label:'',icon:'',image:'',artType:'',color:'#315b68',type:'none',target:'',payload:''}}
function blankPage(){return{name:'Page '+(cfg.pages.length+1),buttons:Array.from({length:9},blankButton)}}
async function load(){cfg=await(await fetch('/api/config')).json();cfg.pages=cfg.pages||[];if(!cfg.pages.length)cfg.pages.push({name:'Page 1',buttons:[]});fillSettings();render()}
function fillSettings(){for(const k of ['name','brightness','ssid','mqttHost','mqttPort','mqttUser','espnowChannel'])$(k).value=cfg[k]??''}
function collectSettings(){for(const k of ['name','ssid','mqttHost','mqttUser'])cfg[k]=$(k).value;for(const k of ['brightness','mqttPort','espnowChannel'])cfg[k]=Number($(k).value);if($('password').value)cfg.password=$('password').value;if($('mqttPassword').value)cfg.mqttPassword=$('mqttPassword').value}
function renderTabs(){$('tabs').innerHTML=cfg.pages.map((p,i)=>`<button class="${i===page?'active':''}" onclick="page=${i};render()">${esc(p.name||'Page '+(i+1))}</button>`).join('')}
function render(){renderTabs();$('pageName').value=cfg.pages[page].name||'';const p=cfg.pages[page];p.buttons=p.buttons||[];while(p.buttons.length<9)p.buttons.push(blankButton());
 $('deck').innerHTML=p.buttons.slice(0,9).map((b,i)=>`<div class="deck-button" data-index="${i}" draggable="true" style="--button:${esc(b.color||'#315b68')}" ondragstart="dragStart(event,${i})" ondragover="dragOver(event,${i})" ondrop="dropButton(event,${i})" ondragend="dragEnd()" onpointerdown="pointerDown(event,${i})" onpointermove="pointerMove(event)" onpointerup="pointerEnd(event)" onpointercancel="pointerCancel(event)">${b.image?`<canvas width="96" height="59" data-asset="${esc(b.image)}"></canvas>`:`<span class="emoji">${esc(b.icon||'')}</span>`}<span class="button-label">${esc(b.label||'')}</span><button class="more" aria-label="Configure button ${i+1}" onclick="event.stopPropagation();openButton(${i})">&hellip;</button></div>`).join('');loadCanvases()}
const helpContent={
 pages:['Pages','<p>Each page contains nine independent buttons. Use <strong>Add page</strong> to create another page and <strong>Delete page</strong> to remove the current one. Show Deck supports 1–12 pages.</p><p>Page actions refer to pages by number, so review those actions after inserting or deleting pages. Swipe left or right on the physical deck to move between pages.</p>'],
 arrange:['Rearranging buttons','<p>Drag a button onto another slot to move it; the buttons between those slots shift to make room. The complete button moves, including its label, artwork, color, action, target, and payload.</p><p>On a phone or tablet, press and hold a button until it highlights, then drag it. Use the three-dot control when you want to configure rather than move it. Press <strong>Save to Show Deck</strong> when the layout is correct.</p>'],
 label:['Button label','<p>The label is the short title drawn along the bottom of the physical button. Labels remain visible over images and emoji artwork with a dark shadow for contrast.</p><p>Short names such as <strong>BLACKOUT</strong>, <strong>CANDLES</strong>, or <strong>SCENE 3</strong> work best on the 2.8-inch display. The label does not affect the command sent.</p>'],
 color:['Button color','<p>This is the base color of the button. It fills blank buttons and becomes the background behind an emoji or text icon.</p><p>A full-bleed uploaded image covers most of this color. If you change the color behind an existing emoji, edit or re-enter the emoji so its artwork is rendered again with the new background.</p>'],
 emoji:['Emoji and text icons','<p>Enter an emoji or very short text symbol. When you press <strong>Done</strong>, the browser renders it into a bitmap that the ESP32 display can show. Its appearance comes from the emoji font on the phone or computer doing the setup.</p><p>One emoji usually gives the clearest result. Entering an icon replaces uploaded artwork after Done. Animated emoji are not supported.</p>'],
 artwork:['Button artwork','<p>Upload PNG, JPEG, WebP, or another image format your browser can open. The editor center-crops it to fill the 96×59 button artwork area, similar to a Stream Deck key.</p><p>Very small images may look soft after scaling. GIF files currently use only their first frame. Uploading artwork replaces the previous image for this button.</p>'],
 name:['Deck name','<p>The deck name identifies this controller in the setup interface and ESP-NOW messages. It is also converted into a lowercase network hostname; spaces and unsupported hostname characters are removed or changed.</p>'],
 brightness:['Screen brightness','<p>Choose a value from 20 to 255. Lower values reduce glare and power use; higher values improve visibility in bright rooms. The minimum prevents the screen from appearing completely dead.</p>'],
 wifi:['Wi-Fi connection','<p>Enter the show-control network name if this deck should use MQTT, HTTP, OTA updates, or network access to its editor. If connection fails—or the SSID is blank—the deck starts its <strong>ShowDeck-Setup</strong> hotspot.</p><p>ESP-NOW can operate without a router. When Wi-Fi and ESP-NOW are used together, the ESP-NOW receivers must use the Wi-Fi access point\'s channel.</p>'],
 mqtt:['MQTT broker','<p>Enter the broker hostname or IP address without <code>http://</code>. Port <code>1883</code> is typical for an unencrypted broker. Username and password are optional if your local broker permits anonymous connections.</p><p>MQTT buttons publish one message when tapped. This is useful for Home Assistant, Node-RED, lighting gateways, and show-control services subscribed to a topic.</p>'],
 espnow:['ESP-NOW channel','<p>Every ESP-NOW sender and receiver must be on the same 2.4 GHz channel. A fixed channel such as 6 works well for a router-free show rig.</p><p>If Show Deck joins Wi-Fi, its radio follows the access point channel. Set this field and all receivers to that same channel. ESP-NOW does not require an SSID or internet connection.</p>']
};
const actionDetails={
 none:{name:'None',summary:'The button is visual only and sends no command.',target:'Target is ignored. You can still use a label, color, emoji, or image as a divider or status reference.',payload:'Payload is ignored.'},
 setup:{name:'Setup',summary:'Starts the ShowDeck-Setup hotspot so a nearby phone or computer can open the editor.',target:'Target is ignored for Setup.',payload:'Payload is ignored for Setup.'},
 espnow:{name:'ESP-NOW',summary:'Broadcasts a low-latency command directly to nearby ESP32 receivers without a router or internet connection.',target:'Use the receiver group programmed into your props, such as <code>all</code>, <code>all_candles</code>, or <code>bar</code>. Group names are case-sensitive and are limited to 23 characters.',payload:'Enter the command your receiver firmware understands, such as <code>preset:3</code>, <code>power:off</code>, or <code>flame:blue</code>. The current packet allows up to 63 characters.'},
 mqtt:{name:'MQTT',summary:'Publishes one message to the MQTT broker configured in Settings. Home Assistant or Node-RED can subscribe and run a scene, automation, or flow.',target:'Enter a topic such as <code>showdeck/bar/cue</code> or <code>homeassistant/button/showdeck</code>. Use a consistent topic hierarchy so show controls are easy to maintain.',payload:'Enter the exact text to publish, such as <code>ON</code>, <code>blackout</code>, or a JSON object. Messages use the broker connection in Settings and are sent once per tap.'},
 http:{name:'HTTP',summary:'Calls a local device or web endpoint. This works well with WLED, Node-RED HTTP-in nodes, Home Assistant webhooks, and custom show-control services.',target:'Enter the complete URL beginning with <code>http://</code>, for example <code>http://192.168.10.50/json/state</code>. The endpoint must be reachable from the deck\'s Wi-Fi network.',payload:'Leave Payload blank to send GET. Enter a JSON body to send POST with <code>Content-Type: application/json</code>, for example <code>{"ps":3}</code> for a WLED preset.'},
 page:{name:'Page',summary:'Changes the physical Show Deck to another configured page without sending a network command.',target:'Enter the destination page number from 1 to '+12+'. Page numbers follow the tab order; if pages are deleted, verify these buttons still point to the intended page.',payload:'Payload is ignored for Page actions.'}
};
function showHelp(topic){let title,body;if(topic==='action'){title='Button actions';body='<p>Each tap runs one action. Macros and multi-step sequences are planned but are not part of this release.</p>'+Object.values(actionDetails).map(a=>'<h3>'+a.name+'</h3><p>'+a.summary+'</p>').join('')}else if(topic==='target'||topic==='payload'){const type=$('bType').value,a=actionDetails[type]||actionDetails.none;title=(topic==='target'?'Target':'Payload')+' — '+a.name;let detail=a[topic];if(type==='page'&&topic==='target')detail=detail.replace('1 to 12','1 to '+cfg.pages.length);body='<p>'+a.summary+'</p><h3>'+title.split(' — ')[0]+'</h3><p>'+detail+'</p>'}else{const h=helpContent[topic]||['Help',''];title=h[0];body=h[1]}$('helpTitle').textContent=title;$('helpBody').innerHTML=body;if(!$('helpDialog').open)$('helpDialog').showModal()}
function clearDragMarks(){document.querySelectorAll('.deck-button').forEach(el=>el.classList.remove('dragging','drop-target'))}
function markDrop(i){document.querySelectorAll('.deck-button').forEach(el=>el.classList.toggle('drop-target',Number(el.dataset.index)===i))}
function moveButton(from,to){if(from<0||to<0||from===to)return;const buttons=cfg.pages[page].buttons,[moved]=buttons.splice(from,1);buttons.splice(to,0,moved);render();$('status').textContent='Moved button '+(from+1)+' to slot '+(to+1)+'. Press Save to apply the layout.'}
function dragStart(e,i){if(e.target.closest('.more')){e.preventDefault();return}const el=e.currentTarget;dragFrom=i;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(i));setTimeout(()=>el.classList.add('dragging'),0)}
function dragOver(e,i){e.preventDefault();e.dataTransfer.dropEffect='move';markDrop(i)}
function dropButton(e,i){e.preventDefault();const from=dragFrom>=0?dragFrom:Number(e.dataTransfer.getData('text/plain'));clearDragMarks();dragFrom=-1;moveButton(from,i)}
function dragEnd(){clearDragMarks();dragFrom=-1}
function pointerDown(e,i){if(e.pointerType==='mouse'||e.target.closest('.more'))return;const el=e.currentTarget;touchDrag={from:i,to:i,x:e.clientX,y:e.clientY,id:e.pointerId,el,active:false,timer:setTimeout(()=>{if(!touchDrag)return;touchDrag.active=true;el.classList.add('dragging');try{el.setPointerCapture(e.pointerId)}catch(x){}if(navigator.vibrate)navigator.vibrate(20)},350)}}
function pointerMove(e){const d=touchDrag;if(!d||d.id!==e.pointerId)return;if(!d.active){if(Math.hypot(e.clientX-d.x,e.clientY-d.y)>10)pointerCancel(e);return}e.preventDefault();const hit=document.elementFromPoint(e.clientX,e.clientY),card=hit&&hit.closest('.deck-button');if(card&&card.parentElement===$('deck')){d.to=Number(card.dataset.index);markDrop(d.to)}}
function pointerEnd(e){const d=touchDrag;if(!d||d.id!==e.pointerId)return;clearTimeout(d.timer);const active=d.active,from=d.from,to=d.to;touchDrag=null;clearDragMarks();if(active)moveButton(from,to)}
function pointerCancel(e){if(!touchDrag)return;clearTimeout(touchDrag.timer);touchDrag=null;clearDragMarks()}
function openButton(i){editing=i;const b=cfg.pages[page].buttons[i];$('buttonTitle').textContent='Button '+(i+1);$('bLabel').value=b.label||'';$('bIcon').value=b.icon||'';$('bColor').value=b.color||'#315b68';$('bType').value=b.type||'none';$('bTarget').value=b.target||'';$('bPayload').value=b.payload||'';updateActionHelp();if(!$('buttonDialog').open)$('buttonDialog').showModal()}
function edit(k,v){cfg.pages[page].buttons[editing][k]=v}
function editType(v){edit('type',v);updateActionHelp()}
function updateActionHelp(){const type=$('bType').value,h={none:['No command is sent. Use this for a display-only button.','Not used for this action.','Not used for this action.'],setup:['Opens the Show Deck setup hotspot.','Not used for this action.','Not used for this action.'],espnow:['Sends a router-free command to ESP-NOW receivers.','Receiver group such as all_candles, bar, or all.','Command understood by the receiver, such as preset:3 or power:off.'],mqtt:['Publishes a message to your MQTT broker.','MQTT topic such as showdeck/bar/cue.','Value to publish, such as ON, blackout, or JSON.'],http:['Calls a device, webhook, Node-RED, or Home Assistant URL.','Complete http:// URL, such as http://192.168.10.50/json/state.','Leave blank for GET. Enter a JSON body for POST, such as {"ps":3}.'],page:['Changes to another page on this Show Deck.','Page number from 1 to '+cfg.pages.length+'.','Not used for this action.']}[type]||['','',''];$('actionHelp').textContent=h[0];$('targetHelp').textContent=h[1];$('payloadHelp').textContent=h[2];$('bTarget').placeholder=type==='http'?'http://...':type==='mqtt'?'showdeck/topic':type==='espnow'?'all_candles':type==='page'?'1-'+cfg.pages.length:'';const unused=type==='none'||type==='setup'||type==='page';$('bPayload').disabled=unused;$('bTarget').disabled=type==='none'||type==='setup'}
function editIcon(v){const b=cfg.pages[page].buttons[editing];b.icon=v;b.artType='emoji'}
async function finishButton(){const b=cfg.pages[page].buttons[editing],hasIcon=(b.icon||'').trim();if(b.artType==='emoji'||(hasIcon&&!b.image)){if(hasIcon)await renderIcon();else await removeImage(false)}$('buttonDialog').close();render()}
function openSettings(){fillSettings();$('settingsDialog').showModal()}
function assetName(){const b=cfg.pages[page].buttons[editing],old=(b.image||'').replace('/','');return old.startsWith('asset_')?old:`asset_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}.rgb`}
async function canvasToAsset(canvas){const d=canvas.getContext('2d').getImageData(0,0,96,59).data;let hex='';for(let i=0;i<d.length;i+=4){const v=((d[i]>>3)<<11)|((d[i+1]>>2)<<5)|(d[i+2]>>3);hex+=(v&255).toString(16).padStart(2,'0')+(v>>8).toString(16).padStart(2,'0')}const name=assetName(),r=await fetch('/api/asset?name='+name,{method:'POST',headers:{'Content-Type':'text/plain'},body:hex});if(!r.ok)throw Error(await r.text());cfg.pages[page].buttons[editing].image='/'+name}
async function renderIcon(){const b=cfg.pages[page].buttons[editing],c=document.createElement('canvas');c.width=96;c.height=59;const x=c.getContext('2d');x.fillStyle=b.color||'#315b68';x.fillRect(0,0,96,59);x.font='44px "Apple Color Emoji","Segoe UI Emoji",system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(b.icon||'?',48,29);try{await canvasToAsset(c);b.artType='emoji';$('status').textContent='Emoji artwork applied.'}catch(e){$('status').textContent='Emoji upload failed: '+e.message;throw e}}
function uploadImage(el){const f=el.files[0];if(!f)return;const img=new Image(),url=URL.createObjectURL(f);img.onload=async()=>{const c=document.createElement('canvas');c.width=96;c.height=59;const x=c.getContext('2d'),b=cfg.pages[page].buttons[editing];x.fillStyle=b.color||'#315b68';x.fillRect(0,0,96,59);const scale=Math.max(96/img.width,59/img.height),w=img.width*scale,h=img.height*scale;x.drawImage(img,(96-w)/2,(59-h)/2,w,h);URL.revokeObjectURL(url);try{await canvasToAsset(c);b.artType='image';render();openButton(editing);$('status').textContent=f.type==='image/gif'?'GIF first frame uploaded. Full animation is planned.':'Full-button image uploaded.'}catch(e){$('status').textContent='Image upload failed: '+e.message}};img.onerror=()=>{$('status').textContent='The selected image could not be read.';URL.revokeObjectURL(url)};img.src=url;el.value=''}
async function removeImage(refresh=true){const b=cfg.pages[page].buttons[editing];if(b.image)await fetch('/api/asset?name='+encodeURIComponent(b.image.replace('/','')),{method:'DELETE'});b.image='';b.artType='';if(refresh){render();openButton(editing)}}
async function resetButton(){if(!confirm('Reset this button to blank?'))return;const old=cfg.pages[page].buttons[editing];if(old.image)await fetch('/api/asset?name='+encodeURIComponent(old.image.replace('/','')),{method:'DELETE'});cfg.pages[page].buttons[editing]=blankButton();render();openButton(editing);$('status').textContent='Button reset locally. Press Save to apply the change.'}
async function loadCanvases(){for(const c of document.querySelectorAll('canvas[data-asset]')){try{const r=await fetch('/api/asset?name='+encodeURIComponent(c.dataset.asset.replace('/',''))),a=new Uint8Array(await r.arrayBuffer()),h=a.length/(96*2),tmp=document.createElement('canvas');tmp.width=96;tmp.height=h;const tx=tmp.getContext('2d'),im=tx.createImageData(96,h);for(let i=0,j=0;i<a.length;i+=2,j+=4){const v=a[i]|(a[i+1]<<8);im.data[j]=((v>>11)&31)*255/31;im.data[j+1]=((v>>5)&63)*255/63;im.data[j+2]=(v&31)*255/31;im.data[j+3]=255}tx.putImageData(im,0,0);c.getContext('2d').drawImage(tmp,0,0,96,59)}catch(e){}}}
function addPage(){if(cfg.pages.length>=12){$('status').textContent='The current limit is 12 pages.';return}cfg.pages.push(blankPage());page=cfg.pages.length-1;render();$('pageName').focus()}
async function deletePage(){if(cfg.pages.length===1){$('status').textContent='Show Deck must keep at least one page.';return}if(!confirm('Delete this page and all nine buttons?'))return;for(const b of cfg.pages[page].buttons||[]){if(b.image)await fetch('/api/asset?name='+encodeURIComponent(b.image.replace('/','')),{method:'DELETE'})}cfg.pages.splice(page,1);if(page>=cfg.pages.length)page=cfg.pages.length-1;render();$('status').textContent='Page removed locally. Press Save to apply the change.'}
async function save(){collectSettings();$('status').textContent='Saving...';try{const r=await fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg)});$('status').textContent=r.ok?'Saved to Show Deck.':'Save failed: '+await r.text()}catch(e){$('status').textContent='Save failed: connection lost ('+e.message+')'}}
function downloadConfig(){collectSettings();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(cfg,null,2)],{type:'application/json'}));a.download='show-deck-config.json';a.click()}
function importConfig(el){const f=el.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{cfg=JSON.parse(r.result);page=0;fillSettings();render();$('status').textContent='Imported locally. Press Save to send it to Show Deck.'}catch(e){$('status').textContent='Invalid JSON file.'}};r.readAsText(f)}
load().catch(e=>$('status').textContent='Could not load configuration: '+e)
</script></body></html>
)HTML";
